import { Image, FileText, Scissors, Video, FileArchive, ArrowRightLeft } from 'lucide-react';

export const categories = ['All', 'Popular', 'Image Tools', 'PDF Tools', 'Video Tools'];

export const tools = [
  {
    id: 'background-remover',
    title: 'AI Background Remover',
    description: 'Instantly remove the background from any image with one click.',
    Icon: Scissors,
    category: 'Image Tools',
    href: '#',
  },
  {
    id: 'image-converter',
    title: 'Image Converter',
    description: 'Convert images to and from JPG, PNG, WEBP, and more.',
    Icon: Image,
    category: 'Image Tools',
    href: '#',
  },
  {
    id: 'image-compressor',
    title: 'Image Compressor',
    description: 'Reduce the file size of your images without losing quality.',
    Icon: Image,
    category: 'Image Tools',
    href: '#',
  },
  {
    id: 'pdf-converter',
    title: 'PDF Converter',
    description: 'Convert PDFs to Word, Excel, JPG, and vice-versa.',
    Icon: FileText,
    category: 'PDF Tools',
    href: '#',
  },
  {
    id: 'pdf-merger',
    title: 'PDF Merger',
    description: 'Combine multiple PDF files into a single document.',
    Icon: FileText,
    category: 'PDF Tools',
    href: '#',
  },
  {
    id: 'pdf-splitter',
    title: 'PDF Splitter',
    description: 'Extract specific pages or split a PDF into multiple files.',
    Icon: FileText,
    category: 'PDF Tools',
    href: '#',
  },
  {
    id: 'pdf-compressor',
    title: 'PDF Compressor',
    description: 'Shrink the size of your PDF files for easy sharing.',
    Icon: FileText,
    category: 'PDF Tools',
    href: '#',
  },
  {
    id: 'mp4-to-gif',
    title: 'MP4 to GIF',
    description: 'Create animated GIFs from your favorite video clips.',
    Icon: Video,
    category: 'Video Tools',
    href: '#',
  },
  {
    id: 'mp4-to-mp3',
    title: 'Video to MP3',
    description: 'Extract audio from a video file and save it as an MP3.',
    Icon: Video,
    category: 'Video Tools',
    href: '#',
  },
  {
    id: 'zip-extractor',
    title: 'ZIP Extractor',
    description: 'Unzip compressed files online without any software.',
    Icon: FileArchive,
    category: 'File Tools',
    href: '#',
  },
  {
    id: 'file-compressor',
    title: 'File Compressor (ZIP)',
    description: 'Create a ZIP archive from multiple files.',
    Icon: FileArchive,
    category: 'File Tools',
    href: '#',
  },
  {
    id: 'all-converters',
    title: 'All Converters',
    description: 'Access over 50 different file conversion tools.',
    Icon: ArrowRightLeft,
    category: 'Converters',
    href: '#',
  },
];
